name: CI/CD for challenge N5

on:
  push:
    branches:
      - develop
      - testing
permissions:
      id-token: write
      contents: read
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Manejo de variables de entorno
        run: |
          if [[ "${{ github.head_ref }}" == "develop" ]]; then
            echo "ENVIRONMENT_NAME=Develop" >> $GITHUB_ENV
          elif [[ "${{ github.head_ref }}" == "testing" ]]; then
            echo "ENVIRONMENT_NAME=Testing" >> $GITHUB_ENV
          fi        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          output-credentials: true

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: n5-challenge
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG     
          echo "image=$REGISTRY/$REPOSITORYY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: n5-task-definition-revision4.json
          container-name: n5        
          image: ${{ steps.build-image.outputs.image }}
          
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
            task-definition: ${{ steps.task-def.outputs.task-definition }}
            service: ${{ secrets.ECS_SERVICE }}
            cluster: ${{ secrets.ECS_CLUSTER }}
            wait-for-service-stability: true 